name: CD Pipeline
on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed
jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Pull image from Docker
      run: docker pull munguriek/nodeapp:latest
    - name: Delete old  container
      run: docker rm -f nodeapp || true
    - name: Run latest docker container
      run: docker run -d -p 8000:3000 --name nodeapp munguriek/nodeapp